jmad/jmad/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from rest_framework import routers

from albums.views import AlbumViewSet, TrackViewSet
from solos.views import SoloViewSet

router = routers.SimpleRouter()
router.register(r'albums', AlbumViewSet)
router.register(r'tracks', TrackViewSet)
router.register(r'solos', SoloViewSet)

urlpatterns = [
    # API
    url(r'^api/', include(router.urls)),

    # Admin
    url(r'^admin/', include(admin.site.urls)),

    # Apps
    url(r'^$', 'solos.views.index'),
    url(
        r'^recordings/(?P<album>[\w-]+)/(?P<track>[\w-]+)/(?P<artist>[\w-]+)/$',
        'solos.views.solo_detail',
        name='solo_detail_view'
    ),
]

jmad/albums/models.py
from django.db import models


class Album(models.Model):

    name = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    slug = models.SlugField()

    class Meta(object):
        ordering = ['name']

    def __str__(self):
        return self.name


class Track(models.Model):

    name = models.CharField(max_length=100)
    album = models.ForeignKey(Album)
    track_number = models.PositiveIntegerField(blank=True, null=True)
    slug = models.SlugField()

    class Meta(object):
        ordering = ['album', 'track_number']

    def __str__(self):
        return self.name

jmad/solos/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.text import slugify

import musicbrainzngs as mb

from albums.models import Album, Track

mb.set_useragent('JMAD – http://jmad.us/', version='0.0.1')


class Solo(models.Model):
    track = models.ForeignKey(Track)
    artist = models.CharField(max_length=100)
    instrument = models.CharField(max_length=50)
    start_time = models.CharField(max_length=20, blank=True, null=True)
    end_time = models.CharField(max_length=20, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)

    class Meta:
        ordering = ['track', 'start_time']

    def get_absolute_url(self):
        return reverse('solo_detail_view', kwargs={
            'album': self.track.album.slug,
            'track': self.track.slug,
            'artist': self.slug
        })

    def get_duration(self):
        duration_string = ''
        if self.start_time and self.end_time:
            duration_string = '{}-{}'.format(self.start_time, self.end_time)
        return duration_string

    @classmethod
    def get_artist_tracks_from_musicbrainz(cls, artist):
        """
        Create Album, Track, and Solo records for artists we find
        in the MusicBrainz API
        :param artist: an artist's name as a string to search for
        :return: Queryset of Solos
        """
        search_results = mb.search_artists(artist)
        best_result = search_results['artist-list'][0]
        instrument = Solo.get_instrument_from_musicbrainz_tags(best_result['tag-list'])
        for album_dict in mb.browse_releases(best_result['id'], includes=['recordings'])['release-list']:
            album = Album.objects.create(
                name=album_dict['title'],
                artist=artist,
                slug=slugify(album_dict['title'])
            )
            for track_dict in album_dict['medium-list'][0]['track-list']:
                track = Track.objects.create(
                    album=album,
                    name=track_dict['recording']['title'],
                    track_number=track_dict['position'],
                    slug=slugify(track_dict['recording']['title'])
                )
                Solo.objects.create(
                    track=track,
                    artist=artist,
                    instrument=instrument,
                    slug=slugify(artist)
                )

        return Solo.objects.filter(artist=artist)

    @classmethod
    def get_instrument_from_musicbrainz_tags(cls, tag_list):
        """
        Return a single instrument from a list of dict-tags as returned in the MusicBrainzNGS API
        :param tag_list: a list of dicts with keys 'count' and 'name'
        :return: a string
        """
        instrument_map = {'pianist': 'piano', 'bassist': 'bass'}
        return instrument_map[set(instrument_map.keys()).intersection([tag['name'] for tag in tag_list]).pop()]

jmad/albums/views.py
from rest_framework import viewsets, mixins

from .models import Album, Track
from .serializers import AlbumSerializer, TrackSerializer


class AlbumViewSet(viewsets.GenericViewSet, mixins.ListModelMixin, mixins.RetrieveModelMixin):

    queryset = Album.objects.all()
    serializer_class = AlbumSerializer


class TrackViewSet(viewsets.GenericViewSet, mixins.ListModelMixin, mixins.RetrieveModelMixin):

    queryset = Track.objects.all()
    serializer_class = TrackSerializer

jmad/solos/views.py
from django.shortcuts import render_to_response

import musicbrainzngs as mb
from rest_framework import viewsets, mixins

from .models import Solo
from .serializers import SoloSerializer

mb.set_useragent('JMAD - http://jmad.us/', version='0.0.1')


def index(request):
    context = {'solos': []}

    if request.GET.keys():
        solos_queryset = Solo.objects.all()

        if request.GET.get('instrument'):
            solos_queryset = solos_queryset.filter(instrument=request.GET['instrument'])

        artist_kwarg = request.GET.get('artist', None)
        if artist_kwarg:
            solos_queryset = solos_queryset.filter(artist=artist_kwarg)

        context['solos'] = solos_queryset

        if context['solos'].count() == 0 and artist_kwarg:
            context['solos'] = Solo.get_artist_tracks_from_musicbrainz(artist_kwarg)

    return render_to_response('solos/index.html', context)


def solo_detail(request, album, track, artist):  # pylint: disable=unused-argument
    context = {
        'solo': Solo.objects.get(slug=artist, track__slug=track, track__album__slug=album)
    }
    return render_to_response('solos/solo_detail.html', context)


class SoloViewSet(viewsets.GenericViewSet, mixins.CreateModelMixin, mixins.RetrieveModelMixin):

    queryset = Solo.objects.all()
    serializer_class = SoloSerializer

jmad/solos/templates/solos/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <a class="navbar-brand">JMAD</a>
    <form>
        <label for="jmad-instrument">Instrument</label>
        <input type="text" class="form-control" id="jmad-instrument" name="instrument" placeholder="i.e. trumpet" />
        <label for="jmad-artist">Artist</label>
        <input type="text" class="form-control" id="jmad-artist" name="artist" placeholder="i.e. Davis" />
        <button type="submit">Search JMAD</button>
    </form>

    {% for solo in solos %}
        <div class="jmad-search-result">
             <a href="{{ solo.get_absolute_url }}">
                 {{ solo.track }}: {{ solo.artist }} on {{ solo.instrument }}
             </a>
        </div>
    {% endfor %}
</body>
</html>

jmad/solos/templates/solos/solo_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p id="jmad-artist">{{ solo.artist }}</p>
    <p id="jmad-track">
        {{ solo.track.name }}
        {% with solos=solo.track.solo_set.count %}
           [{{solos}} solo{{ solos|pluralize }}]
       {% endwith %}
    </p>
    <p id="jmad-album">
        {{ solo.track.album.name }}
        {% with tracks=solo.track.album.track_set.count %}
           [{{tracks}} track{{ tracks|pluralize }}]
       {% endwith %}
    </p>
    <p id="jmad-start-time">{{ solo.start_time }}</p>
    <p id="jmad-end-time">{{ solo.end_time }}</p>
</body>
</html>